site_name: Music Besties Documentation
site_description: Comprehensive documentation for the Music Besties application
theme:
  name: material
  palette:
    primary: indigo
    accent: pink
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - 1. Introduction & Version Information: index.md
  - 2. Application Overview: application_overview/overview.md
  - 3. Core Screens: screens/screens.md
  - 4. Component Details: components/components.md
  - 5. Design System:
      - Overview: design_system/index.md
      - Foundations: design_system/foundations.md
      - Components: design_system/components.md
      - Patterns: design_system/patterns.md
      - Accessibility: design_system/accessibility.md
      - Responsive Design: design_system/responsive.md
  - 6. User Interactions: interactions/interactions.md
  - 7. Technical Implementation: technical_implementation/technical.md
  - 8. User Experience: user_experience/user_experience.md
  - 9. Developer Implementation Guide: developer_guide/guide.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true

plugins:
  - search
